name: Django CI

on:
  push:
    branches: [ restaurante_master ]
  pull_request:
    branches: [ restaurante_master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r reservas/requirements.txt
    - name: Run Tests
      run: |
        python reservas/manage.py test